version: '3.1'

services:

  watcher:
    container_name: watcher
#    ports:
#      - "27017:27017"
    build: .
    networks:
      - script
    volumes:
      - ./accs:/src/accs
    restart: always

networks:
  script: